### ISSUE TITLE
Project is dead ?

### ISSUE THREAD

**Issue by almeidajeff** [RadioFreeAsia/rfa.kaltura#96]
Hi,
Is anyone still working on this project?
I would like to know if it has been tested with Plone 4.3.9 and if the case contributes with improvements.

;)

**Comment by almeidajeff** [comment]
@flipmcf ?

**Comment by flipmcf** [comment]
I'm not currently working on it,  but it is in use - at least here.

**Comment by flipmcf** [comment]
Project is not dead.  Just no need to change things.
